# Generated by Django 3.2.6 on 2021-10-07 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('email_verified_hash', models.CharField(default='000000', max_length=32, verbose_name='Verify Token')),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.CharField(default='https://assets.servatom.com/notefy/avatars/parrot.png', max_length=400, verbose_name='avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
